### ISSUE TITLE
Defining association structures

### ISSUE THREAD

**Issue by ellessenne** [boennecd/VAJointSurv#4]
Hi @boennecd,
I have been using {VAJointSurv} a bit more lately and I have a comment regarding the definition of the association structure(s) between the survival and longitudinal sub-model(s).
I reckon this is more of a _design_ question, not really a bug/issue with the package per se, so feel free to ignore this!

Here's an example of fitting a univariate joint model using an example dataset:

``` r
library(joineRML)
library(VAJointSurv)
library(dplyr)

data(heart.valve)
hvd <- na.omit(heart.valve)

m1 <- marker_term(
  log.lvmi ~ sex + age,
  id = num,
  data = hvd,
  time_fixef = ns_term(x = time, df = 3),
  time_rng = poly_term(x = time, degree = 1, intercept = TRUE, raw = TRUE)
)

# Expected value association structure
surv_obj <- surv_term(
  Surv(fuyrs, status) ~ age,
  id = num,
  data = distinct(hvd, num, fuyrs, status, age),
  time_fixef = ns_term(x = fuyrs, df = 3)
)
comp_obj <- joint_ms_ptr(
  markers = list(m1),
  survival_terms = surv_obj,
  max_threads = 4L
)
start_val <- joint_ms_start_val(comp_obj)
opt_out <- joint_ms_opt(object = comp_obj, par = start_val)
fmt_est <- joint_ms_format(object = comp_obj, opt_out$par)
```

This uses the default settings, e.g., the expected value association structure.
No problem with that.

However, if one wants to use, e.g., the cumulative value association structure, my understanding is that it has to be defined in the `surv_term()` object, via the `ders` argument: 

```r
# Cumulative value association structure:
surv_obj_2 <- surv_term(
  Surv(fuyrs, status) ~ age,
  id = num,
  data = distinct(hvd, num, fuyrs, status, age),
  time_fixef = ns_term(x = fuyrs, df = 3), 
  ders = list(-1)
)
comp_obj_2 <- joint_ms_ptr(
  markers = list(m1),
  survival_terms = surv_obj_2,
  max_threads = 4L
)
start_val_2 <- joint_ms_start_val(comp_obj_2)
opt_out_2 <- joint_ms_opt(object = comp_obj_2, par = start_val_2)
fmt_est_2 <- joint_ms_format(object = comp_obj_2, opt_out_2$par)
```

While I understand that the association coefficients eventually appear in the survival sub-model, I was expecting this option to be in the `joint_ms_ptr()` function: the rationale would be that, in principle, this defines how the longitudinal and survival components are linked.
Further to that, it doesn't feel necessarily obvious what the order of the longitudinal sub-models would be, if more than one is present.
The interface I had in my mind would lead to something like the pseudo-code below:

```r
jm <- joint_ms_ptr(
  markers = list(m1, m2, m3),
  survival_terms = surv_obj,
  ders = list(-1, 0, 1)
)
```

Now, I don't know if the current implementation is because of the internal structure of the package – if that was the case, I guess it would be quite complex to update the interface.
And possibly not really worth it?
Nevertheless, I look forward to hear your thoughts about this and would be happy to chat at any time if that would be easier!

Many thanks,

Alessandro

**Comment by boennecd** [comment]
This is a great suggestion! The API might have to be a bit different when there are multiple survival models. For instance, take this example in the README https://github.com/boennecd/VAJointSurv/blob/3c777ec89f7efb92dbfbfa0f751b3954bcfbfdc2/vignettes/VAJointSurv.Rmd#L2740-L2764

with `ders` being assigned here https://github.com/boennecd/VAJointSurv/blob/3c777ec89f7efb92dbfbfa0f751b3954bcfbfdc2/vignettes/VAJointSurv.Rmd#L2538-L2542

This could be changed to 

```r
surv_terminal <- surv_term(
  Surv(y, event) ~ Z1, id = id, dat$terminal_outcome,
  time_fixef = bs_term(y, knots = 5, Boundary.knots = c(0, 10)), 
  with_frailty = TRUE)
surv_obs <- surv_term(
  Surv(lf_trunc, y, event) ~ 1, id = id, dat$obs_process,
  time_fixef = ns_term(y, knots = 5, Boundary.knots = c(0, 10)), 
  with_frailty = TRUE)
comp_obj <- joint_ms_ptr(markers = list(marker_1, marker_2),
                         survival_terms = list(surv_terminal, surv_obs),
                         ders = ders,
                         max_threads = 4L)
```

I.e. the `ders` argument has to be a list of lists with integer vectors. It can be list of integer vectors when there is only one survival sub model.

> Now, I don't know if the current implementation is because of the internal structure of the package – if that was the case, I guess it would be quite complex to update the interface.

It actually should not be too bad. `ders` is simply added to the `surv_term` object here without any checks here https://github.com/boennecd/VAJointSurv/blob/3c777ec89f7efb92dbfbfa0f751b3954bcfbfdc2/R/surv_term.R#L117-L119

A default value in `joint_ms_ptr ` is then added here if `ders` is `NULL`  https://github.com/boennecd/VAJointSurv/blob/3c777ec89f7efb92dbfbfa0f751b3954bcfbfdc2/R/joint_surv_VA.R#L91-L95

The new `ders` lists then has to assigned here for each `surv_term` object in the new API.

The list of `surv_term` objects are then passed to C++ here https://github.com/boennecd/VAJointSurv/blob/3c777ec89f7efb92dbfbfa0f751b3954bcfbfdc2/R/joint_surv_VA.R#L121-L123

This does not have to be changed.

**Comment by ellessenne** [comment]
Interesting! I did not consider the case of multiple survival outcomes, where – as you say – lists of lists might be used. 
What would be the case if different markers are to be used in the different survival sub-models, e.g., marker 1 and 2 for survival outcome 1, while marker 1 only for survival outcome 2? Is that currently supported?

Glad to hear it would be relatively easy to update the API though!

**Comment by boennecd** [comment]
> What would be the case if different markers are to be used in the different survival sub-models, e.g., marker 1 and 2 for survival outcome 1, while marker 1 only for survival outcome 2? Is that currently supported?

That might work at the moment but I have never tested it. The lists of lists are mapped into `std::vector<std::vector<int> >` here https://github.com/boennecd/VAJointSurv/blob/3c777ec89f7efb92dbfbfa0f751b3954bcfbfdc2/src/survival-term.h#L52

and as an `std::vector<unsigned>` here for the number of association parameters that a given survival model has for each marker in the indexer object https://github.com/boennecd/VAJointSurv/blob/3c777ec89f7efb92dbfbfa0f751b3954bcfbfdc2/src/VA-parameter.h#L33

Quickly glancing through the code, it might work already to simply do 

```r
 ders <- list( 
   list(c(-1L, 0L), # cumulative and present value  
        integer()),        # no association
   list(integer(),         # no association
        c(0L, 1L))) # present value and derivative 
```

Otherwise, it should be easy to make that work. 

Alternatively, you can use the `mask` argument in `joint_ms_opt` and `joint_ms_profile` for now and set the appropriate association parameter to be fixed and equal to zero. Some care might need to be taken then when using `joint_ms_hess` where the masked indices should be excluded.

**Comment by ellessenne** [comment]
Interesting – I think the former approach would be better than the latter, which (as you say) feels quite error-prone to me. 
Thanks!

**Comment by boennecd** [comment]
The `ders` argument has now been moved to `joint_ms_ptr`.
